### PR TITLE
Added toggle function

### PR DESCRIPTION
**Pull request by JairoMartinezA**
Hi Alex,

Could you review these changes? basically was added one option to toggle the display of the unicode name.

### CODE REVIEW

**Comment by Alexey-T** [comment]
if config file is not exist yet, you get `enabled==False`, but it should be `True`, no?

**Comment by Alexey-T** [comment]
I used to have `import os`, but not `from os import path`, can you change it?

**Comment by JairoMartinezA** [comment]
Sure, let me change those approaches.

**Comment by JairoMartinezA** [comment]
Ready Alex!

**Comment by Alexey-T** [comment]
I see that enabled=False, then you assign to enabled ONLY if config file exists. so if file not exists, enabled will be false?

**Comment by JairoMartinezA** [comment]
Oooh come on, yes you are right. I only change when is reading the ini file to accept a default value. Let me see.

**Comment by JairoMartinezA** [comment]
Ready Alex, I suppose now is OK. 👍

**Pull request merged**
